### ISSUE TITLE
Bug in importeren data set: bestaande entries worden niet bijgewerkt

### ISSUE THREAD

**Issue by EliasZ** [ansien/now-inzichtelijk#5]
```
SELECT company_name, COUNT(*)
FROM batch_entry
GROUP BY company_name
HAVING COUNT(*) > 1
```

Even snel naar gekeken, maar komt waarschijnlijk doordat er wordt gezocht naar een entry, maar die entry is dan nog niet geflushed. Hierdoor wordt hij nog niet gevonden in de transactie en maakt hij alsnog een nieuwe aan.
Zit in al die import scripts (`findOrCreateEntry`) .

Voorbeeld hiervan is "ZAANKRACHT UITZENDBUREAU SCHIPHOL B.V" die dubbel in `first-batch-0.csv` zit (r137649).

**Comment by ansien** [comment]
Ah, liep hier inderdaad ook al tegenaan ja. Zal er even induiken binnenkort.

**Comment by ansien** [comment]
Lijkt nog steeds niet helemaal goed te gaan:

![image](https://user-images.githubusercontent.com/1700132/109426033-a526f000-79eb-11eb-8ecc-d447298d2b20.png)

**Comment by EliasZ** [comment]
@ansien ook een gevalletje andere opmaak in de input zoals genoemd met het voorbeeld van zaankracht uitzendbureau: https://github.com/ansien/now-inzichtelijk/pull/6#issue-579558817

```
V.O.F. HANDELSONDERNEMING R. HOEFNAGEL
V.O.F. HANDELSONDERNEMING           R. HOEFNAGEL
```

Hiervoor moet er nog iets van sanitizing/formatting toegevoegd worden om extra spaties weg te halen.

**Comment by ansien** [comment]
@tjidde-nl Dat zou inderdaad een betere oplossing zijn qua database design. Zal binnenkort even knutselen!

**Comment by ansien** [comment]
Opgelost
