### ISSUE TITLE
Verschillen NOW1

### ISSUE THREAD

**Issue by tdn131** [ansien/now-inzichtelijk#7]
In het dashboard is per saldo € 7.415.110.042 (137.075 aanvragen volgens first-batch-1.csv) NOW1 opgenomen. Dit moet mijns inziens € 7.419.465.987 zijn (137.155 aanvragen).

Er lijkt een verschil te zijn tussen het gepubliceerde Excel bestand van 09-11-2020 (aanmaakdatum en wijzigingsdatum 09-12-2020) en de PDF van 19-11-2020 (aanmaakdatum 17-11-2020). Ik hanteer daarom het Excel bestand als up to date. Zie: https://www.uwv.nl/overuwv/pers/documenten/2020/gegevens-ontvangers-now-1-0-regeling.aspx

Opvallend is het verschil bij bedrijfsnaam ORANJEFLEX B.V. te Schiphol:
Niet voorkomend in PDF en dashboard, maar in Excel € 8.475.507.

P.S. Het bestand third-batch-0.csv gebruikt de komma om te splitsen en de andere CSV bestanden gebruiken puntkomma. Ook gebruikt third-batch.csv niet Nederlandse getalnotering in tegenstelling tot de anderen. Bijzondere tekens, zoals é worden in alle CSV bestanden vertaald worden naar Ã©, dit heeft met de codering te maken.

**Comment by tdn131** [comment]
@ansien Mogelijk heb je hier geen notificatie van gekregen. Zou je misschien naar bovenstaande kunnen kijken? Alvast bedankt.

**Comment by ansien** [comment]
@tdn131 Dag,

Heb hier nog geen tijd voor gehad. Pull requests zijn altijd welkom :)

**Comment by tdn131** [comment]
De NOW 4 lijst is vandaag ook beschikbaar geworden. 

NOW1: https://www.uwv.nl/overuwv/pers/documenten/2020/gegevens-ontvangers-now-1-0-regeling.aspx
NOW2: https://www.uwv.nl/overuwv/pers/documenten/2020/register-tweede-aanvraagperiode-now.aspx
NOW3: https://www.uwv.nl/overuwv/pers/documenten/2021/register-derde-aanvraagperiode-now.aspx
NOW4: https://www.uwv.nl/overuwv/pers/documenten/2021/register-vierde-aanvraagperiode-now.aspx

Ik denk dat de Excel bestanden een stuk eenvoudiger te extracten zijn dan de PDFjes. Ze hebben een eenvoudige structuur.

**Comment by ansien** [comment]
@tdn131 Top, zal 'm er morgenavond even in importeren.

**Comment by ansien** [comment]
Done!
