### ISSUE TITLE
Register NOW7 beschikbaar en NOW1 aangepast

### ISSUE THREAD

**Issue by tdn131** [ansien/now-inzichtelijk#8]
@ansien Sinds kort is het register NOW7 beschikbaar: https://www.uwv.nl/overuwv/pers/documenten/2022/register-zevende-aanvraagperiode-now.aspx

Daarnaast is NOW1 geüpdatet en bevat naast het voorschot ook de vastgestelde som. Zie https://www.uwv.nl/overuwv/pers/documenten/2022/register-eerste-aanvraagperiode-now.aspx

Na het inlezen van alle recente Excel bestanden kom ik op de volgende totalen:

NOW | Voorschot | Vastgesteld | Aantal
-- | -- | -- | --
1 | 7.286.515.112 | 4.538.421.397 | 137.239
2 | 4.241.653.963 |   | 63.629
3 | 2.776.555.051 |   | 78.235
4 | 3.243.177.762 |   | 75.895
5 | 2.012.121.907 |   | 45.353
6 | 1.068.527.651 |   | 26.793
7 | 919.303.737 |   | 41.119

Zou je de website kunnen updaten? Alvast bedankt!

**Comment by ansien** [comment]
Bedankt voor de info. Zal ik komende week even oppakken!

**Comment by ansien** [comment]
@tdn131 Staat live!

**Comment by tdn131** [comment]
Dag @ansien. Thanks voor het aanpassen. 

Ik zie nog wel wat geks. Jouw som van voorschot (€ 21.547.726.899) en aantal toekenningen (468.253) komen niet overeen met mijn lijst.
Ik kom op totaal € 21.547.855.183 (verschil € 128.284) en aantal 468.263 (verschil 10 stuks). Ik heb je CSV bestandjes gedownload en door Power BI gehaald. Jouw CSV bestanden sluiten met mijn bedragen. Het lijkt alsof er iets verdwijnt in je transformatie, want het inlezen is juist. Hoor graag!

**Comment by ansien** [comment]
@tdn131 

Iemand op Reddit had dit ook gevonden inderdaad. Zal hier binnenkort als ik weer wat tijd vrij heb even induiken. Tijdens het omzetten van de Excel naar CSV is iets niet helemaal lekker gegaan en zijn bepaalde rijen opgesplitst geraakt.
